### PR TITLE
#162569502 Create a Sign Up form

### PR DESCRIPTION
**Pull request by matthenge**
#### What does this PR do?
Create a user Sign-Up page
#### Description of Task to be completed?
1. Add a HTML file
2. Add a CSS file
3. Add a sign up form
#### How should this be manually tested?
Clone the repository to your local machine [here](https://github.com/matthenge/StackOverflow-lite.git) and open using a browser.
#### Any background context you want to provide?
This is just the UI templates with no other added functionality
#### What are the relevant pivotal tracker stories?
https://www.pivotaltracker.com/story/show/162569502
#### Screenshots 
screenshot from 2018-12-14 17-54-30

### CODE REVIEW

**Comment by wachiranduati** [comment]
looks nice :100:

**Comment by a-braham** [comment]
Your UI looks fantastic man

**Comment by tirgei** [comment]
Your UI looks nice.

I can see you've selected you want to merge this branch to master. Check on that, we're supposed to merge to gh-pages

**Comment by SolomonMacharia** [comment]
Nice UI. Great job.

**Pull request merged**
